project/apps/coffee/urls.py
import django.views.generic
from django.urls import path
from django.views.decorators.cache import cache_page
import project.apps.about.views
from . import views
from .views import *
app_name = 'coffee'

urlpatterns = [
    path('', cache_page(60)(CoffeeList.as_view()), name='coffee'),
    path('create', Create.as_view(), name='create'),
    path('<int:pk>', Info.as_view(), name='info'),
    path('<int:pk>/update', Update.as_view(), name='update'),
    path('<int:pk>/delete', Delete.as_view(), name='delete'),
    path('about', project.apps.about.views.about, name='about'),
    path('contact', contact, name='contact'),
    path('<int:pk>/add_feedback/', CreateFeedback.as_view(), name='add_feedback'),
    path('registration/', SignUp.as_view(), name='registration'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),


]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("__debug__/", include("debug_toolbar.urls")),
                  path('captcha/', include('captcha.urls')),
                  path('coffee/', include('project.apps.coffee.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

    urlpatterns = [
                      path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/coffee/models.py
from django.db import models


class Coffee(models.Model):
    title = models.CharField('Название', max_length=20)
    description = models.CharField('Описание', max_length=100)
    price = models.DecimalField('Цена', max_digits=10, decimal_places=2)
    pictures = models.ImageField(upload_to='coffee/img', default='0.jpg')
    info = models.TextField('Описание', max_length=1000)

    def __str__(self):
        return f'{self.pk}, {self.title}, {self.description}, {self.price}, {self.info}'

    def get_absolute_url(self):
        return f'/coffee'

    class Meta:
        verbose_name = 'Кофе'
        verbose_name_plural = 'Кофе'


class Feedback(models.Model):
    user = models.CharField('Пользователь', max_length=50)
    text = models.TextField('Текст отзыва')
    rating = models.IntegerField('Рейтинг')
    coffees = models.ForeignKey(Coffee, on_delete=models.CASCADE, related_name='feedbacks')

    def __str__(self):
        return self.user

    class Meta:
        verbose_name = "Отзывы"
        verbose_name_plural = "Отзывы"
        ordering = ['-rating']

project/apps/coffee/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Coffee, Feedback


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'})),
    first_name = forms.CharField(label='Firstname', widget=forms.TextInput(attrs={'class': 'form-input'})),
    last_name = forms.CharField(label='Lastname', widget=forms.TextInput(attrs={'class': 'form-input'})),
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'})),
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'})),
    password2 = forms.CharField(label='RPassword', widget=forms.PasswordInput(attrs={'class': 'form-input'})),

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'})),
    # email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'})),
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'})),

    class Meta:
        model = User
        fields = ('usernamr', 'password')


class CoffeeForm(forms.ModelForm):
    class Meta:
        model = Coffee
        fields = '__all__'

        widgets = {
            "title": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Name coffee'
            }),
            "description": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Description'
            }),
            "info": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Info'
            }),
            "price": forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Price'
            }),
            "pictures": forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'accept': 'image/*'
            })
        }


class FeedbackForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Feedback
        fields = ['text', 'rating', 'captcha']

        widgets = {
            "text": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Description'
            }),
            "rating": forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'rating'
            })
        }

project/apps/coffee/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.core.files.base import ContentFile
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, DeleteView, CreateView, ListView

from .forms import CoffeeForm, FeedbackForm, RegisterUserForm, LoginUserForm
from .models import Coffee, Feedback


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'coffee/login.html'

    def get_success_url(self):
        return reverse_lazy('coffee:coffee')


def logout_user(request):
    logout(request)
    return redirect('coffee:login')


class SignUp(CreateView):
    form_class = RegisterUserForm
    success_url = reverse_lazy("coffee:coffee")
    template_name = 'coffee/registration.html'

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     c_def = self.get_user_context(title='Registration')
    #     return dict(list(context.items()) + list(c_def.items()))


class CoffeeList(ListView):
    model = Coffee
    template_name = 'coffee/coffee.html'
    context_object_name = 'coffees'
    queryset = Coffee.objects.order_by('price')


#   def coffee(request):
#       coffees = Coffee.objects.order_by('price')
#       return render(request, 'coffee/coffee.html', {'coffees': coffees})


def contact(request):
    return render(request, 'coffee/contact.html', )


# def user_login(request):
#     if request.method == "POST":
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request,
#                                 user_login=cd['username'],
#                                 password=cd['password']
#                                 )
#             if user is not None:
#                 if user.is_active():
#                     login(request, user)
#                     return HttpResponse('Authenticated successfully')
#                 else:
#                     return HttpResponse('Disabled account')
#         else:
#             return HttpResponse('Invalid logun')
#     else:
#         form = LoginForm()
#     return render(request, 'login.html', {'form': form})


class Create(CreateView):
    model = Coffee
    template_name = 'coffee/create_coffee.html'
    form_class = CoffeeForm

    def form_valid(self, form):
        self.object = form.save(commit=False)

        picture = self.request.FILES.get('picture')
        if isinstance(picture, InMemoryUploadedFile):
            picture_data = picture.read()
            self.object.picture.save(picture.name, ContentFile(picture_data), save=False)

        self.object.save()
        return super().form_valid(form)


class Info(DetailView):
    model = Coffee
    template_name = 'coffee/info.html'
    context_object_name = 'coffee'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        coffees = self.object
        feedbacks = coffees.feedbacks.all()
        context['feedbacks'] = feedbacks
        return context


class Update(UpdateView):
    model = Coffee
    template_name = 'coffee/update_coffee.html'
    form_class = CoffeeForm


class Delete(DeleteView):
    model = Coffee
    template = 'coffee/coffee_confirm_delete.html'
    success_url = '/coffee/'


class CreateFeedback(CreateView):
    model = Feedback
    template_name = 'coffee/create_feedback.html'
    form_class = FeedbackForm

    def form_valid(self, form):
        coffee_id = self.kwargs['pk']
        try:
            coffees = Coffee.objects.get(pk=coffee_id)
        except Coffee.DoesNotExist:
            raise Http404("Coffee does not exist")

        feedback = form.save(commit=False)

        if self.request.user.is_authenticated:
            feedback.user = self.request.user.username

        feedback.coffees = coffees
        feedback.save()

        return HttpResponseRedirect(reverse('coffee:info', kwargs={'pk': coffee_id}))

# def add_feedback(request, pk):
#     error = ''
#     if request.method == 'POST':
#         form = FeedbackForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('info')
#         else:
#             error = 'Invalid form input'
#             print("FORM ERRORS", form.error)
#
#         form = FeedbackForm
#
#         data = {
#             'form': form,
#             'error': error
#         }
#         return render(request, 'create_feedback.html', data)
#
# def create(request):
#     error = ''
#     if request.method == 'POST':
#         form = CoffeeForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('coffee')
#         else:
#             error = 'Invalid form input'
#             print("Form errors:", form.errors)
#
#     form = CoffeeForm()
#
#     data = {
#         'form': form,
#         'error': error
#     }
#     return render(request, 'coffee/create_coffee.html', data)

# def update(request, pk):
#     error = ''
#     coffee_instance = Coffee.objects.get(pk=pk)
#     if request.method == "POST":
#         form = CoffeeForm(request.POST, request.FILES, instance=coffee_instance)
#         if form.is_valid():
#             form.save()
#             return redirect('coffee')
#         else:
#             error = 'Invalid form input'
#             print("Form errors:", form.errors)
#     else:
#         form = CoffeeForm(instance=coffee_instance)
#
#         data = {
#             'form': form,
#             'pk': pk,
#             'error': error
#         }
#         print("debug:", data)
#         return render(request, 'coffee/update_coffee.html', data)

# def delete(request, pk):
#     coffee_instance = get_object_or_404(Coffee, pk=pk)
#     if request.method == 'POST':
#         coffee_instance.delete()
#         print('confirm')
#         return redirect('coffee')
#     return render(request, 'coffee/coffee_confirm_delete.html', {'coffee_instance': coffee_instance})

project/apps/coffee/templates/coffee/coffee.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Virtual Coffee Shop</title>
    <link rel="stylesheet" type="text/css" href="{% static 'coffee/css/main.css' %}">
</head>
<body>

<header>
    <div class="header-content">
        <h1>Welcome to Virtual Coffee Shop</h1>
        <p>Your Perfect Cup Awaits</p>
    </div>
</header>
<nav>
    <ul class="horizontal-list">
        <li><a href="{% url 'coffee:about' %}" class="btn-1">About Us</a></li>
        <li><a href="{% url 'coffee:contact' %}" class="btn-1">Contact Us</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'coffee:logout' %}" class="btn-1">Log out</a></li>
        {% else %}
            <li><a href="{% url 'coffee:login' %}" class="btn-1">Log in</a></li>
        {% endif %}
    </ul>
</nav>

<div class="container">
    {% if coffees %}
    {% for coffee in coffees %}
    <a class="menu-item-link" href="{% url 'coffee:info' coffee.pk %}">
        <div class="menu-item">
            <img src="{{ coffee.pictures.url }}" alt="{{ coffee.title }}">
            <div>
                <h3>{{ coffee.title }}</h3>
                <p>{{ coffee.description }}</p>
            </div>
            <span>${{ coffee.price }}</span>
        </div>
    </a>
    {% endfor %}
    {% else %}
    <p>No coffee available</p>
    {% endif %}
</div>

<div class="footer">
    <p>&copy; 2023 Virtual Coffee Shop. All rights reserved.</p>
</div>

</body>
</html>

project/apps/coffee/templates/coffee/coffee_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'coffee/css/create.css' %}">
    <title>Delete Coffee</title>
</head>
<body>
    <header>
        <h1>Welcome to Virtual Coffee Shop</h1>
        <p>Your Perfect Cup Awaits</p>
    </header>
    <div class="center-content">
        <div class="container">
            <h1>Delete Coffee</h1>
            <p>Are you sure you want to delete the following coffee?</p>
            <p><strong>Title:</strong> {{ coffee.title }}</p>
            <p><strong>Description:</strong> {{ coffee.description }}</p>
            <p><strong>Price:</strong> ${{ coffee.price }}</p>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Delete</button>
                <a class="btn btn-secondary" href="{% url 'coffee:coffee' %}">Cancel</a>
            </form>
        </div>
    </div>
    <div class="footer">
        <p>&copy; 2023 Virtual Coffee Shop. All rights reserved.</p>
    </div>
</body>
</html>

project/apps/coffee/templates/coffee/create_coffee.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'coffee/css/create.css' %}">
    <title>Create Coffee</title>
</head>
<body>
    <header>
        <h1>Welcome to Virtual Coffee Shop</h1>
        <p>Your Perfect Cup Awaits</p>
    </header>
    <div class="center-content">
        <div class="container">
            <h1>Form for creating coffee</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.title }}<br>
                {{ form.description }}<br>
                {{ form.info }}<br>
                {{ form.price }}<br>
                {{ form.pictures }}<br>
                <span>{{ error }}</span>
                <button class="btn btn-success" type="submit">Add Coffee</button>
            </form>
        </div>
    </div>
    <div class="footer">
        <p>&copy; 2023 Virtual Coffee Shop. All rights reserved.</p>
    </div>
</body>
</html>

project/apps/coffee/templates/coffee/create_feedback.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'coffee/css/create.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <title>Create Rating</title>
</head>
<body>
    <header>
        <h1>Welcome to Virtual Coffee Shop</h1>
        <p>Your Perfect Cup Awaits</p>
    </header>
    <div class="center-content">
        <div class="container">
            <h1>Form for creating rating</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.text }}<br>
                {{ form.captcha }}<br>
                <div class="rating">
                    <span class="star" data-rating="1">☆</span>
                    <span class="star" data-rating="2">☆</span>
                    <span class="star" data-rating="3">☆</span>
                    <span class="star" data-rating="4">☆</span>
                    <span class="star" data-rating="5">☆</span>
                </div>
                <input type="hidden" name="rating" value="1" id="rating">
                <span>{{ error }}</span>
                <button class="btn btn-success" type="submit">Add Rating</button>
            </form>
        </div>
    </div>
    <div class="footer">
        <p>&copy; 2023 Virtual Coffee Shop. All rights reserved.</p>
    </div>

    <script>
        const stars = document.querySelectorAll('.star');
        const ratingInput = document.querySelector('#rating');

        stars.forEach(star => {
            star.addEventListener('click', () => {
                const rating = star.getAttribute('data-rating');
                ratingInput.value = rating;
                stars.forEach(s => s.classList.remove('selected'));
                star.classList.add('selected');
            });
        });
    </script>
</body>
</html>

project/apps/coffee/templates/coffee/info.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'coffee/css/info.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <title>Virtual Coffee Shop</title>
</head>
<body>
<header>
    <h1>Welcome to Virtual Coffee Shop</h1>
    <p>Your Perfect Cup Awaits</p>
</header>
<div class="container">
    <div class="menu-item">
        <h1>{{ coffee.title }}</h1>
        <p>{{ coffee.info }}</p>
        <ul class="horizontal-list">
        <a href="{% url 'coffee:coffee'  %}" class="btn-1">Home</a>
        </ul>
    </div>
</div>

<nav>
    <ul class="horizontal-list">
        <li>
            <a href="#" class="btn-1" id="feedback-button" data-authenticated="{% if request.user.is_authenticated %}true{% else %}false{% endif %}">Leave Your Feedback Here</a>
        </li>
    </ul>
</nav>
<p></p>
<div class="container">
    <h2>Your feedback helps to make this coffee even tastier:</h2>
    <ul>
        {% for feedback in feedbacks %}
            <div class="review-divider">
                <p>{{ feedback.user }}</p>
                <li>
                    <div class="rating">
                        {% for i in "12345" %}
                            {% if i|add:0 == feedback.rating %}
                                <i class="fas fa-star"></i>
                            {% else %}
                                <i class="far fa-star"></i>
                            {% endif %}
                        {% endfor %}
                    </div>
                    {{ feedback.text }}
                </li>
            </div>
        {% endfor %}
    </ul>
</div>
<script>
    document.getElementById('feedback-button').addEventListener('click', function(e) {
        e.preventDefault();
        {% if not request.user.is_authenticated %}
            alert("You must log in to leave a feedback.");
        {% else %}
            window.location.href = "{% url 'coffee:add_feedback' pk=coffee.pk %}";
        {% endif %}
    });
</script>
<div class="footer">
    <p>&copy; 2023 Virtual Coffee Shop. All rights reserved.</p>
</div>
</body>
</html>

project/apps/coffee/templates/coffee/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Virtual Coffee Shop</title>
    <link rel="stylesheet" type="text/css" href="{% static 'coffee/css/main.css' %}">

</head>
<body>

<header>
    <div class="header-content">
        <h1>Welcome to Virtual Coffee Shop</h1>
        <p>Your Perfect Cup Awaits</p>
    </div>
</header>
<nav>
    <ul class="horizontal-list">
        <li><a href="{% url 'coffee:about' %}" class="btn-1">About Us</a></li>
        <li><a href="{% url 'coffee:contact' %}" class="btn-1">Contact Us</a></li>
        <li><a href="{% url 'coffee:coffee' %}" class="btn-1">Home</a></li>
    </ul>
</nav>

<form class="registration-form" method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors}}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Login</button>
    <p>If you don't have an existing account, you can <a href="{% url 'coffee:registration' %}">Register</a></p>
</form>
<div class="footer">
    <p>&copy; 2023 Virtual Coffee Shop. All rights reserved.</p>
</div>

</body>
</html>

project/apps/coffee/templates/coffee/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Virtual Coffee Shop</title>
    <link rel="stylesheet" type="text/css" href="{% static 'coffee/css/main.css' %}">
</head>
<body>

<header>
    <div class="header-content">
        <h1>Welcome to Virtual Coffee Shop</h1>
        <p>Your Perfect Cup Awaits</p>
    </div>
</header>
<nav>
    <ul class="horizontal-list">
        <li><a href="{% url 'coffee:about' %}" class="btn-1">About Us</a></li>
        <li><a href="{% url 'coffee:contact' %}" class="btn-1">Contact Us</a></li>
        <li><a href="{% url 'coffee:coffee' %}" class="btn-1">Home</a></li>
    </ul>
</nav>

<form class="registration-form" method="post">
    {% csrf_token %}
    <label for="id_username">Username</label>
    <input type="text" name="username" id="id_username" placeholder="Username">

    <label for="id_first_name">First Name</label>
    <input type="text" name="first_name" id="id_first_name" placeholder="First Name">

    <label for="id_last_name">Last Name</label>
    <input type="text" name="last_name" id="id_last_name" placeholder="Last Name">

    <label for="id_email">Email</label>
    <input type="email" name="email" id="id_email" placeholder="Email">

    <label for="id_password1">Password</label>
    <input type="password" name="password1" id="id_password1" placeholder="Password">

    <label for="id_password2">Confirm Password</label>
    <input type="password" name="password2" id="id_password2" placeholder="Confirm Password">

    <button type="submit">Register</button>
    <p>If you already have an existing account, click on <a href="{% url 'coffee:login' %}">Sign up</a></p>
</form>

<div class="footer">
    <p>&copy; 2023 Virtual Coffee Shop. All rights reserved.</p>
</div>

</body>
</html>

project/apps/coffee/templates/coffee/update_coffee.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'coffee/css/create.css' %}">
    <title>Update Coffee</title>
</head>
<body>
    <header>
        <h1>Welcome to Virtual Coffee Shop</h1>
        <p>Your Perfect Cup Awaits</p>
    </header>
    <div class="center-content">
        <div class="container">
            <h1>Form for creating coffee</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="_method" value="PUT">
                {{ form.title }}<br>
                {{ form.description }}<br>
                {{ form.info }}<br>
                {{ form.price }}<br>
                {{ form.pictures }}<br>
                <span>{{ error }}</span>
                <button class="btn btn-success" type="submit">Update Coffee</button>
            </form>
        </div>
        </div>
    </div>
    <div class="footer">
        <p>&copy; 2023 Virtual Coffee Shop. All rights reserved.</p>
    </div>
</body>
</html>